export RANK=$SLURM_PROCID
export WORLD_RANK=$SLURM_PROCID
export LOCAL_RANK=$SLURM_LOCALID
export WORLD_SIZE=$SLURM_NTASKS
export MASTER_PORT=29500 # default from torch launcher
export WANDB_START_METHOD="thread"
export TOTAL_BATCH_SIZE=$((SLURM_NNODES * 4))

echo RANK=$RANK
echo WORLD_RANK=$WORLD_RANK
echo LOCAL_RANK=$LOCAL_RANK
echo WORLD_SIZE=$WORLD_SIZE
echo TOTAL_BATCH_SIZE=$TOTAL_BATCH_SIZE
